// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// Follow the instructions in the README to configure your Firebase project.
// This configuration will be automatically updated with your project's
// credentials after you connect your project.

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

export function getFirebaseConfig() {
  // Development mode: return mock config if no API key is provided
  if (!firebaseConfig.apiKey) {
    console.warn('Firebase config not found, using mock configuration for development');
    return {
      apiKey: 'mock-api-key',
      authDomain: 'mock-project.firebaseapp.com',
      projectId: 'mock-project',
      storageBucket: 'mock-project.appspot.com',
      messagingSenderId: '123456789',
      appId: 'mock-app-id',
    };
  }
  return firebaseConfig;
}
